name: Gradle Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [8, 11, 17]
    runs-on: ${{ matrix.os }}
    name: Java ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - uses: gradle/gradle-build-action@v2
    - run: ./gradlew clean build
